ragatalasearch/home/urls.py
from django.urls import path, include
from . import views

app_name= 'home'
urlpatterns = [
    path('', views.HomeView.as_view() , name= 'home'),
    path('about/',views.AboutView.as_view(), name='about')
]

ragatalasearch/ragas/urls.py
from django.urls import path
from . import views

app_name = 'ragas'
urlpatterns=[
    path('',views.SearchRaga.as_view(), name= "search"),
    path('raga/',views.RagaListView.as_view(), name = 'name'),
    path('raga/<int:pk>/',views.RagaDetailView.as_view(), name ='raga_detail'),
    path('arohana/', views.RagaArListView.as_view(), name='arohana'),
    path('arohana/<int:pk>/', views.RagaDetailView.as_view(), name='raga_ar_detail'),
    path('avarohana/', views.RagaAvListView.as_view(), name='avarohana'),
    path('avarohana/<int:pk>/', views.RagaDetailView.as_view(), name='raga_av_detail'),
    path('table',views.RagaTableView.as_view(), name='raga_table'),
    path('table/<int:pk>/', views.RagaMelaDetailView.as_view(),name='raga_mela_detail'),
]

ragatalasearch/ragatalasearch/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('ragas/', include('ragas.urls')),
    path('talas/',include('talas.urls')),
    path('admin/', admin.site.urls),
]

ragatalasearch/talas/urls.py
from django.urls import path
from . import views 

app_name= 'talas'
urlpatterns=[
    path('name/',views.TalaNameListView.as_view(),name='tala_namelist'),
    path('name/<int:pk>/',views.TalaDetailView.as_view(),name='tala_detail'),
    path('aksharas/', views.TalaAkListView.as_view(), name='tala_list'),
    path('aksharas/<int:pk>/',views.TalaDetailView.as_view(),name='tala_ak_detail'),
    path('table/', views.TalaTableView.as_view(), name="tala_table"),
]

ragatalasearch/home/models.py
from django.db import models

# Create your models here.

ragatalasearch/ragas/models.py
from django.db import models

class Melakarta(models.Model):
    name = models.CharField(max_length= 128)
    num = models.IntegerField(default =0)
    def __str__(self):
        return self.name

class Raga(models.Model):
    name = models.CharField(max_length= 128)
    arohanam = models.CharField(max_length = 256)
    avarohanam = models.CharField(max_length = 256)
    mela_true = models.BooleanField(default= False)
    mela = models.ForeignKey(Melakarta , on_delete= models.CASCADE)

    def __str__(self):
        return self.name

ragatalasearch/talas/models.py
from django.db import models

class TalaCategory(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Tala(models.Model):
    name= models.CharField(max_length=128)
    angas = models.CharField(max_length=512)
    aksharas = models.IntegerField(default=0)
    category = models.ForeignKey(TalaCategory, on_delete= models.CASCADE)

    def __str__(self):
        return self.name

ragatalasearch/home/views.py
from django.shortcuts import render
from django.views import View

class HomeView(View):
    def get(self, request):
        return render(request, 'home/main.html')

class AboutView(View):
    def get(self,request):
        return render(request,'home/about.html')        

ragatalasearch/ragas/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from ragas.models import Raga, Melakarta
from django.views.generic import DetailView

class SearchRaga(View):
    def get(self,request):
        return render(request, 'ragas/raga_search.html')

class RagaListView(View):
    template_name = 'ragas/raga_list.html'

    def get(self,request):
        strval = request.GET.get("search", False)
        raga_exact = None
        if strval:
            raga_list = Raga.objects.all().filter(name__contains = strval).select_related()
        else:
            #raga_list = Raga.objects.all()[:5]
            raga_list = None
            
        ctx ={'raga_list':raga_list , 'search':strval}
        return render(request, self.template_name, ctx)

class RagaArListView(View):
    template_name = 'ragas/raga_ar_list.html'

    def get(self, request):
        strval = request.GET.get("search", False)
        if strval:
            raga_list = Raga.objects.all().filter(arohanam__contains = strval.rstrip()).select_related()
        else:
            raga_list = None
        ctx = {'raga_list':raga_list, 'search':strval}       
        return render(request, self.template_name, ctx)       

class RagaAvListView(View):
    template_name = 'ragas/raga_av_list.html'

    def get(self, request):
        strval = request.GET.get("search", False)
        if strval:
            raga_list = Raga.objects.all().filter(avarohanam__contains = strval.rstrip()).select_related()
        else:
            raga_list = None
        ctx = {'raga_list':raga_list, 'search':strval}       
        return render(request, self.template_name, ctx)   

class RagaTableView(View):
    template_name='ragas/raga_table.html'
    def get(self, request):
        mela_list = Raga.objects.all().filter(mela_true=True) 
        return render(request, self.template_name, {'mela_list':mela_list})       


class RagaDetailView(DetailView):
    model =Raga
    template_name = 'ragas/raga_detail.html'
    def get(self, request, pk):
        x = Raga.objects.all().get(id= pk)
        ctx = {'raga': x}
        return render(request, self.template_name, ctx)

class RagaMelaDetailView(DetailView):
    model = Raga
    template_name = 'ragas/raga_mela_detail.html'
    def get(self, request, pk):
        x = Raga.objects.all().get(id=pk)
        y = Raga.objects.all().filter(mela_id = x.mela_id)[1:]
        ctx = {'raga':x,'janyas':y} 
        return render(request, self.template_name, ctx)       

ragatalasearch/talas/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import DetailView
from .models import Tala
from django.http import HttpResponse

class TalaNameListView(View):
    template_name = 'talas/tala_namelist.html'
    def get(self,request):
        strval = request.GET.get("search",False)
        if strval:
            tala_list = Tala.objects.all().filter(name__contains=strval)
        else:
            tala_list=None
        ctx = {'tala_list':tala_list,'search':strval}   
        return render(request,self.template_name,ctx) 

class TalaAkListView(View):
    template_name='talas/tala_list.html'
    def get(self,request):
        strval = request.GET.get("search",False)
        if strval :
            tala_list = Tala.objects.all().filter(aksharas=strval)
        else:
            tala_list = None
        ctx = {'tala_list':tala_list,'search':strval}  
        return render(request, self.template_name, ctx)      

class TalaDetailView(DetailView):
    model = Tala
    template_name = 'talas/tala_detail.html'
    def get(self,request,pk):
        x = Tala.objects.all().get(id = pk)
        ctx = {'tala':x}
        return render(request, self.template_name, ctx)   

class TalaTableView(View):
    template_name= 'talas/tala_table.html'
    def get(self,request):
        strval = request.GET.get("search", False)
        if strval:
            tala_table = Tala.objects.all().filter(category__name= strval.rstrip())     
        else:
            tala_table = None
        ctx = {'tala_table':tala_table, 'search':strval}
        return render(request, self.template_name, ctx)             

ragatalasearch/home/templates/base_bootstrap.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'style.css' %}"> 

        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
       <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
      <link rel="manifest" href="{% static 'site.webmanifest' %}">
        {% block head %}
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
     {% block navbar %}
        <nav class="navbar fixed-top navbar-expand-md navbar-dark navbar-custom">
            <!-- Brand -->
            
            <a class="navbar-brand" href="{% url 'home:home' %}">
              Raga Tala Search</a>
            <!-- Toggler/collapsibe Button -->
            <div class="nav-pos">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
              <span class="navbar-toggler-icon"></span>
            </button></div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav ">
               
                <li class="nav-item" >
                  <a class="nav-link"  href="{% url 'home:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" 
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search ragas</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'ragas:name' %}">Search by Raga name</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'ragas:arohana' %}">Search by Arohanam</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'ragas:avarohana' %}">Search by Avarohanam</a>
                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" 
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Search talas</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'talas:tala_namelist' %}">Search by Tala name</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'talas:tala_list' %}">Search by Aksharas</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'talas:tala_table' %}">Talas</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'ragas:raga_table' %}">Ragas</a>
                </li>
              </ul>
                <ul class="navbar-nav navbar-right">
               <li class="nav-item">
                 <a class="nav-link" href="{% url 'home:about' %}">About</a>
               </li>
                </ul> 
                </div>
              
              </nav>   
    {% endblock %}


    {% block body %}
    <h1>Base</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>  
 
    {% block jsextra %}
    {% endblock %}
</body>
</html>

ragatalasearch/home/templates/home/about.html
{% extends 'base_bootstrap.html' %}

{% block head %}
<title>Raga Tala Search | About</title>
{% endblock %}

{% block body %}
<div class='container-fluid home-div'>
<h1>About <span class="brand">Raga Tala Search</span></h1>
<h3>Raga and Tala Search made easy!</h3>
<h4>Raga</h4>
<p>There are about 950 ragas that you can search here in the following ways: </p>
<p><strong><a href="{% url 'ragas:name' %}">Raga Search by Name:</a> </strong>Search ragas by entering the raga name</p>
<p><strong><a href="{% url 'ragas:arohana' %}">Raga Search by Arohanam: </a></strong>Click on the swaras of the arohanam that you want to search
and find the raga from the list of ragas </p>
<p><strong><a href="{% url 'ragas:avarohana' %}">Raga Search by Avarohanam</a></strong>
    Click on the swaras forming a avarohanam</p>
<h5>Also,</h5>
<p><strong><a href="{% url 'ragas:raga_table' %}">Melakarta table: </a></strong>
    Click on the ragas in the melakarta table 
to get the details of the mela raga and its janya ragas</p>
<h4>Tala</h4>
<p>Search from the list of talas including the 35 talas, Ashtotara shata(108) talas and Mela talas</p>
<p><strong><a href="{% url 'talas:tala_namelist' %}">Tala search by Name: </a></strong>Enter the tala name</p>
<p><strong><a href="{% url 'talas:tala_list' %}">Tala search by aksharas: </a></strong>Get the tala name and angams by entering aksharas</p>
<h5>Also,</h5>
<p><strong><a href="{% url 'talas:tala_table' %}">Tala tables</a></strong> consisting of 35 Talas table
    , Ashtotara shata(108) talas table and Mela talas table.</p>
</div>

<footer>
    <div>
        Developed with ❤️ by <a href="https://divyashreedivya.github.io/music-art-portfolio"  target="_blank" rel="noopener noreferrer" >Divyashree</a>
    </div>
</footer>

{% endblock %}

ragatalasearch/ragas/templates/ragas/raga_ar_list.html
{% extends 'base_bootstrap.html' %}
{% load static %}
{% block head %}
        <title>Raga Tala Search | Raga search by Arohanam</title>
        <link rel="stylesheet" href="{% static 'ragas/ragas.css' %}"/>
{% endblock %} 
{% block body %}
<div class="container-fluid">
       <!-- <a href="{% url 'ragas:search' %}">Back</a>-->
        <h1>Search raga by Arohanam</h1>
        <a href="{% url 'ragas:arohana' %}">Clear</a>
        <br><br>
        <div class="row bts-raga">
        <div class="col-md-3 g1">
        <button class="btn btn-r">S</button>
        <button class="btn btn-r">R1</button>
        <button class="btn btn-r">R2</button>
        <button class="btn btn-r">R3</button>
        </div>
        <div class="col-md-3 g2">
        <button class="btn btn-r">G1</button>
        <button class="btn btn-r">G2</button>
        <button class="btn btn-r">G3</button>
        <button class="btn btn-r">M1</button>
        </div>
        <div class="col-md-3 g3">
        <button class="btn btn-r">M2</button>
        <button class="btn btn-r">P</button>
        <button class="btn btn-r">D1</button>
        <button class="btn btn-r">D2</button>
        </div>
        <div class="col-md-3 g4">
        <button class="btn btn-r">D3</button>
        <button class="btn btn-r">N1</button>
        <button class="btn btn-r">N2</button>
        <button class="btn btn-r">N3</button>
        </div>
        </div>
        <br><br>
        <form>
        <div class="row">
        <div class="col-xs-9 txt">
        <textarea name="search" id="aroh" style="resize:None"
         {% if search %} value="{{search}}"{% endif %}></textarea></div>
         <div class="col-xs-3 bts">
            <button class="btn btn-s" type="submit">Search</button>
            </div>
        </div> 
        </form>
         {% if search %} 
         <p>You searched : {{search}}</p>
          {% if raga_list %}
            
          <ul class="ul-raga">
              {% for raga in raga_list %}
              <li class="li-raga">
                <a href ="{% url 'ragas:raga_ar_detail' raga.id %}">{{raga.name}}</a>
              </li>
              {% endfor %}
          </ul>
          {% else %}
              <p>No ragas</p>
          {% endif %}    
        {% else %}
        <br>
        <p class="clk">Click on the swaras!</p>
        {% endif %}
</div>
{% endblock %}
{% block jsextra %}

    <script type="text/javascript">
    $(document).ready(function(){
        $(".btn-r").click(function(){
            console.log("Button clicked");
            $(this).toggleClass("active");
            $("#aroh").append($(this).text()+" ");
        });
    });
    </script>
{% endblock %} 

ragatalasearch/ragas/templates/ragas/raga_av_list.html
{% extends 'base_bootstrap.html' %}
{% load static %}
{% block head %}
<title>Raga Tala Search | Search by Avarohanam</title>
<link rel="stylesheet" href="{% static 'ragas/ragas.css' %}"/>
{% endblock %}

{% block body %}
<div class="container-fluid">
   <!-- <a href="{% url 'ragas:search' %}">Back</a>-->
    <h1>Search raga by Avarohanam</h1>
    <a href="{% url 'ragas:avarohana' %}">Clear</a>
    <br><br>
    <div class="row bts-raga">
    <div class="col-md-3 g1">
    <button class="btn btn-r">S</button>
    <button class="btn btn-r">R1</button>
    <button class="btn btn-r">R2</button>
    <button class="btn btn-r">R3</button>
    </div>
    <div class="col-md-3 g2">
    <button class="btn btn-r">G1</button>
    <button class="btn btn-r">G2</button>
    <button class="btn btn-r">G3</button>
    <button class="btn btn-r">M1</button>
    </div>
    <div class="col-md-3 g3">
    <button class="btn btn-r">M2</button>
    <button class="btn btn-r">P</button>
    <button class="btn btn-r">D1</button>
    <button class="btn btn-r">D2</button>
    </div>
    <div class="col-md-3 g4">
    <button class="btn btn-r">D3</button>
    <button class="btn btn-r">N1</button>
    <button class="btn btn-r">N2</button>
    <button class="btn btn-r">N3</button>
    </div>
    </div>
    <br><br>
    <form>
        <div class="row">
        <div class="col-xs-9 txt">
        <textarea name="search" id="avaroh" style="resize:None"
         {% if search %} value="{{search}}"{% endif %}></textarea></div>
         <div class="col-xs-3 bts">
            <button class="btn btn-s" type="submit">Search</button>
            </div>
        </div> 
        </form>
          {% if search %}
         <p>You searched : {{search}}</p>
         
          {% if raga_list %}
            
          <ul class="ul-raga">
              {% for raga in raga_list %}
              <li class="li-raga">
                <a href ="{% url 'ragas:raga_av_detail' raga.id %}">{{raga.name}}</a>
              </li>
              {% endfor %}
          </ul>
          {% else %}
              <p>No ragas</p>
          {% endif %}    
        {% else %}
        <br>
        <p class="clk">Click on the swaras!</p>
        {% endif %}
        </div>
{% endblock %}
{% block jsextra %}
    <script type="text/javascript">
    $(document).ready(function(){
        $(".btn-r").click(function(){
            console.log("Button clicked");
            $(this).toggleClass("active");
            $("#avaroh").append($(this).text()+" ");
        });
    });
    </script>
{% endblock %}

ragatalasearch/ragas/templates/ragas/raga_list.html
{% extends 'base_bootstrap.html' %}
{% load static %}
{% block head %}
<title>Raga Tala Search | Search by name</title>
<link rel="stylesheet" href="{% static 'ragas/ragas.css' %}"/>
{% endblock %}
{% block body %}
      <div class="container-fluid">
       <!-- <a href="{% url 'ragas:search' %}">Back</a>-->
        <h1>Search raga by name</h1>
        <a href="{% url 'ragas:name' %}">Clear</i></a></button>
        <br><br>
        <form>
           <div class="row">
             <div class="col-xs-9 txt">
            <input class="form-control" type="text" placeholder="Search.." name="search"
            {% if search %} value="{{ search }}" {% endif %}>
            </div>
            <div class="col-xs-2 bts">
            <button class="btn btn-n" type="submit">Search</button>
            </div>
           </div>
          </form>
          <br>
          {% if search %}
              {% if raga_list %}
            
              <ul class="ul-raga">
                  {% for raga in raga_list %}
                  <li class="li-raga">
                    <a href ="{% url 'ragas:raga_detail' raga.id %}">{{raga.name}}</a>
                  </li>
                  {% endfor %}
              </ul>
              {% else %}
                  <p>No ragas</p>
              {% endif %}    
          {% endif %}
          </div>
{% endblock %}

ragatalasearch/ragas/templates/ragas/raga_mela_detail.html
{% extends 'base_bootstrap.html' %}
{% load static %}
{% block head %}
<title>Raga Tala Search | Raga Table</title>
<link rel="stylesheet" href="{% static 'ragas/ragas.css' %}">
{% endblock %}

{% block body %}
<div class="container-fluid">
<button class="btn btn-b"><a href="{% url 'ragas:raga_table' %}">Back</a></button>
<h1>{{raga.name}}</h1>
<br>
<div class="card">
        <div class="card-body">
        <div class="card-text">
        <p><strong>Arohanam&nbsp;&nbsp;&nbsp;&nbsp;: </strong>{{raga.arohanam}}</p>
        <p>
        <strong>Avarohanam: </strong>    {{raga.avarohanam}}
        </p>
        <hr>

        {% if raga.mela.num == 1 %}
        <p>{{raga.mela.num}} st Mela</p>
        {% elif raga.mela.num == 2 %}
        <p>{{raga.mela.num}} nd Mela</p>
        {% elif raga.mela.num == 3 %}
        <p>{{raga.mela.num}} rd Mela</p>
        {% else %}
        <p>{{raga.mela.num}} th Mela</p>
        {% endif %}
        </div>
        </div></div>
 <h3>Janya Ragas</h3>
 <br>
 {% if janyas %}
 <ul class="ul-raga">
 {% for janya in janyas %}
    <li class="li-raga">
        <a href="{% url 'ragas:raga_detail' janya.id %}">{{janya.name}}</a>
    </li>
{% endfor %}
</ul>
{% endif %}
</div>
{% endblock %}

ragatalasearch/ragas/templates/ragas/raga_search.html
{% extends 'base_bootstrap.html' %}
{% block head %}
        <title>Search Ragas</title>
{% endblock %}
{% block body %} 
        <ul>
            <li><a href="{% url 'ragas:all' %}">Search by raga name</a></li>
            <li><a href="{% url 'ragas:arohana' %}">Search by arohana</a></li>
            <li><a href="{% url 'ragas:avarohana' %}">Search by avarohana</a></li>
        </ul>
{% endblock %}

ragatalasearch/ragas/templates/ragas/raga_table.html
{% extends 'base_bootstrap.html' %}
{% load static %}
{% block head %}
  <title>Raga Tala Search | Raga table</title>
  <link rel="stylesheet" href="{% static 'ragas/ragas.css' %}">
{% endblock %}

{% block body %}
<div class="container-fluid">
<h1>Melakarta ragas</h1>
<br>
{% if mela_list %}
<div class="table table-responsive-sm">
<table>
  <tr>
    <th>Mela number</th>
    <th>Raga</th>
  </tr>
{% for raga in mela_list %}

    <tr>
    
    <td> {{raga.mela.num}} &nbsp;</td>
    <td>
      <a href="{% url 'ragas:raga_mela_detail' raga.id %}"> {{raga.name}}</a>
     
    </td>
 
  </tr></a>
{% endfor %}  
</table>
</div>
{% endif %}
</div>
{% endblock %}

ragatalasearch/talas/templates/talas/tala_list.html
{% extends 'base_bootstrap.html' %}
{% load static %}
{% block head %}
    <title>Raga Tala Search | Search Tala by aksharas</title>
    <link rel="stylesheet" href="{% static 'talas/talas.css' %}">
{% endblock %}
{% block body %}
<div class="container-fluid">
<h1>Search by Number of aksharas in a tala</h1>
<form>
    <div class="row">
    <div class="col-xs-9 txt">    
    <input type="number" class="form-control" placeholder="Enter the aksharas" name="search"
    {% if search %} value="{{search}}" {% endif %}>
    </div>
    <div class="col-xs-3 bts">
    <button class="btn btn-s" type="submit">Search</button>
    </div>
    </div>
</form>
{% if search %}
{% if tala_list %}
<ul class="ul-tala">
    {% for tala in tala_list %}
    <li class="li-tala">
    <a href="{% url 'talas:tala_ak_detail' tala.id %}">{{tala.name}}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No talas</p>
{% endif %}
{% endif %}
</div>
{% endblock %}

ragatalasearch/talas/templates/talas/tala_namelist.html
{% extends 'base_bootstrap.html' %}
{% load static %}
{% block head %}
    <title>Raga Tala Search | Search Tala by name</title>
    <link rel="stylesheet" href="{% static 'talas/talas.css' %}">
{% endblock %}

{% block body %}
<div class="container-fluid">
<h1>Search Tala by Name</h1>
    <form>
        <div class="row">
        <div class="col-xs-9 txt">
        <input type="text" class ="form-control" placeholder="Enter Tala name" name="search"
        {% if search %} value="{{search}}" {% endif %}>
        </div>
        <div class="col-xs-3 bts">
        <button class="btn btn-s" type="submit">Search</button>
        </div></div>
    </form>
{% if search %}
    {% if tala_list %}
    <ul class="ul-tala">
        {% for tala in tala_list %}
        <li class="li-tala">
        <a href="{% url 'talas:tala_detail' tala.id %}">{{tala.name}}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No talas</p>
    {% endif %}
    {% endif %}
</div>
{% endblock %}

ragatalasearch/talas/templates/talas/tala_table.html
{% extends 'base_bootstrap.html' %}
{% load static %}
{% block head %}
    <title>Raga Tala Search | Tala table</title>
    <link rel="stylesheet" href="{% static 'talas/talas.css' %}">
{% endblock %}

{% block body %}
<div class="container-fluid">
    <a href="{% url 'talas:tala_table' %}">Clear</a>
    <br><br>
    <p>Click on the buttons</p>
    <div class="row">
        <div class="col-md-4">
<button class="btn btnclick">Ashtothara shata(108) Talas</button>
</div>
<div class="col-md-4">
<button class="btn btnclick">72 Melakarta talas</button>
</div>
<div class="col-md-4">
<button class="btn btnclick">35 Talas</button>
</div>
</div>
    <form>
        <textarea name="search" id="tala" style="resize:None" class="hidethis"
             {% if search %} value="{{search}}"{% endif %}></textarea>
        <input class="hidethis clbtn" type="submit">
    </form>
   {% if search %}
    {% if tala_table %}
    <h2 class="talah">{{search}}</h2>
    <div class="table table-responsive">
      <table>
          <tr>
              <th>Tala</th>
              <th>Angas</th>
              <th>Aksharas</th>
          </tr>
          {% for tala in tala_table %}
          <tr>
              <td>{{tala.name}}</td>
              <td>{{tala.angas}}</td>
              <td>{{tala.aksharas}}</td>
          </tr>
          {% endfor %}
      </table>
      </div>
      {% else %}
      <p>No tables</p>
      {% endif %}
      {% else %}
      <p></p>
      {% endif %}
</div>
{% endblock %}

{% block jsextra %}
<script type="text/javascript">
    $(document).ready(function(){
        $(".btnclick").click(function(){
            console.log('Button clicked');
            $(this).toggleClass('active');
            $("#tala").append($(this).text());
            $(".clbtn").click();
           
        });
    });
</script>
{% endblock %}